// DO NOT SWAP THE ELEMENTS - OTHERWISE THE SAVED GAMES MAY BE CORRUPTED
// A NEW ELEMENT MUST BE ADDED TO THE END OF THE LIST
enum Nation {
  austriaHungary,
  belgium,
  bulgaria,
  china,
  france,
  germany,
  greatBritain,
  greece,
  italy,
  japan,
  korea,
  mexico,
  mongolia,
  montenegro,
  romania,
  russia,
  serbia,
  turkey,
  usa,
  usNorth,
  usSouth,
}
