library aggressive_player_ai;

import 'dart:io';
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:trench_warfare/core_entities/entities/game_objects/game_object.dart';
import 'package:trench_warfare/core_entities/entities/money/money_unit.dart';
import 'package:trench_warfare/core_entities/enums/nation.dart';
import 'package:trench_warfare/core_entities/enums/production_center_level.dart';
import 'package:trench_warfare/core_entities/enums/production_center_type.dart';
import 'package:trench_warfare/core_entities/enums/terrain_modifier_type.dart';
import 'package:trench_warfare/core_entities/enums/unit_boost.dart';
import 'package:trench_warfare/core_entities/enums/unit_experience_rank.dart';
import 'package:trench_warfare/core_entities/enums/unit_type.dart';
import 'package:trench_warfare/core_entities/game_constants.dart';
import 'package:trench_warfare/screens/game_field_screen/model/data/readers/metadata/dto/map_metadata.dart';
import 'package:trench_warfare/screens/game_field_screen/model/domain/build/build_calculators_library.dart';
import 'package:trench_warfare/screens/game_field_screen/model/domain/game_field/game_field_library.dart';
import 'package:trench_warfare/screens/game_field_screen/model/domain/money/money_storage.dart';
import 'package:trench_warfare/screens/game_field_screen/model/domain/player/ai/player_ai.dart';
import 'package:trench_warfare/screens/game_field_screen/model/domain/player/estimations/estimations.dart';
import 'package:trench_warfare/screens/game_field_screen/model/domain/player/influence_map/influence_map_library.dart';
import 'package:trench_warfare/screens/game_field_screen/model/domain/player/player_library.dart';
import 'package:trench_warfare/shared/helpers/extensions.dart';
import 'package:trench_warfare/shared/utils/math.dart';

part 'aggressive_player_ai.dart';
part 'phases/turn_phase.dart';
part 'phases/money_spending/money_spending_phase.dart';
part 'phases/money_spending/estimations/terrain_modifier/anti_air_gun_estimation.dart';
part 'phases/money_spending/estimations/terrain_modifier/barbed_wire_estimation.dart';
part 'phases/money_spending/estimations/terrain_modifier/land_fort_estimation.dart';
part 'phases/money_spending/estimations/terrain_modifier/mine_field_estimation.dart';
part 'phases/money_spending/estimations/terrain_modifier/terrain_modifier_estimation_data.dart';
part 'phases/money_spending/estimations/terrain_modifier/trench_estimation.dart';
part 'phases/money_spending/estimations/unit_booster/attack_defence_estimator.dart';
part 'phases/money_spending/estimations/unit_booster/commander_estimator.dart';
part 'phases/money_spending/estimations/unit_booster/transport_estimation.dart';
part 'phases/money_spending/estimations/unit_booster/unit_booster_estimation_data.dart';
part 'phases/money_spending/estimations/production_center_estimation.dart';
part 'phases/money_spending/estimations/units_estimation.dart';